name: Build it ship it

on: push

jobs:
  build-windows:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@main
      with:
        ref: complete-ci
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 6.0.x
        include-prerelease: true
    - name: Restore dependencies
      run: dotnet restore
    - name: Build world for windows
      run: |
        & 'C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\Common7\IDE\devenv.com' .\KodAdıAfacanlar.sln /Build 'WorldRelease' /Project '.\KodAdıAfacanlar.Setup.World\KodAdıAfacanlar.Setup.World.vdproj'
  
  build-mac:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@main
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 6.0.x
        include-prerelease: true
    - name: Restore dependencies
      run: dotnet restore

    - name: Build world for mac
      run: dotnet build ./KodAdıAfacanlar/ -t:Clean,BundleApp -p:PublishProfile=MacWorld.pubxml
    - name: Make world executable
      run: chmod +x ./KodAdıAfacanlar/bin/WorldRelease/net6.0/publish/osx-x64/Kod\ Adı\ Afacanlar.app/Contents/MacOS/Kod\ Adı\ Afacanlar
    - name: Zip world
      working-directory: ./KodAdıAfacanlar/bin/WorldRelease/net6.0/publish/osx-x64/
      run: zip -r "Kod Adı Afacanlar - World.app.zip" Kod\ Adı\ Afacanlar.app

    - name: Build time for mac
      run: dotnet build ./KodAdıAfacanlar/ -t:Clean,BundleApp -p:PublishProfile=MacTime.pubxml
    - name: Make executable
      run: chmod +x ./KodAdıAfacanlar/bin/TimeRelease/net6.0/publish/osx-x64/Kod\ Adı\ Afacanlar.app/Contents/MacOS/Kod\ Adı\ Afacanlar
    - name: Zip time
      working-directory: ./KodAdıAfacanlar/bin/TimeRelease/net6.0/publish/osx-x64/
      run: zip -r "Kod Adı Afacanlar - Time.app.zip" Kod\ Adı\ Afacanlar.app

    - name: Create Release
      uses: softprops/action-gh-release@v1
      if: startsWith(github.ref, 'refs/tags/')
      with:
        files: |
            "./KodAdıAfacanlar/bin/TimeRelease/net6.0/publish/osx-x64/Kod Adı Afacanlar - Time.app.zip"
            "./KodAdıAfacanlar/bin/TimeRelease/net6.0/publish/osx-x64/Kod Adı Afacanlar - World.app.zip"
      
