name: Mac Build

on: push

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@main
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 6.0.x
        include-prerelease: true
    - name: Restore dependencies
      run: dotnet restore
    - name: Build for mac
      run: dotnet build ./KodAdıAfacanlar/ -t:Clean,BundleApp -p:PublishProfile=MacTime.pubxml
    - name: Make executable bin\TimeRelease\net6.0\publish\osx-x64
      run: chmod +x ./KodAdıAfacanlar/bin/TimeRelease/net6.0/publish/osx-x64/Kod\ Adı\ Afacanlar.app/Contents/MacOS/Kod\ Adı\ Afacanlar
    - name: Zip
      working-directory: ./KodAdıAfacanlar/bin/TimeRelease/net6.0/publish/osx-x64/
      run: zip -r "Kod Adı Afacanlar.app.zip" Kod\ Adı\ Afacanlar.app
    - name: Create Release
      uses: softprops/action-gh-release@v1
      if: startsWith(github.ref, 'refs/tags/')
      with:
        files: "./KodAdıAfacanlar/bin/TimeRelease/net6.0/publish/osx-x64/Kod Adı Afacanlar.app.zip"
      
